### PR TITLE
Added icon in FilterPanel.jsx

### PR DESCRIPTION
**Pull request by LyndonTomas**
This is to check if the missing icon is indeed restored in FilterPanel.jsx

### CODE REVIEW

**Review by nikkieyabut — COMMENTED** [review]
Package-lock.json

**Review by jp-ong — CHANGES_REQUESTED** [review]
Contents of package-lock.json does not match ours
Fix by:
1. switch back to dev branch and grab contents of the package-lock.json
2. replace your branch's package-lock.json with the one from dev
3.  push and re-request review

**Review by jp-ong — APPROVED** [review]
🙏

**Review by jp-ong — APPROVED** [review]
💯

**Review by nikkieyabut — COMMENTED** [review]
.

**Review by jp-ong — APPROVED** [review]
🙏 🙏

**Pull request merged**
